controllers/lagoonbuild_controller.go
main.go

This adds support for defining the Fastly no-cache service ID for the cluster the controller is running in.
It will inject the variable `LAGOON_FASTLY_NOCACHE_SERVICE_ID` into all Lagoon builds that are started by this controller if the `fastly-watch-status` flag is set to true.

Add Fastly service ID configuration to the controller

---

controllers/helpers.go
controllers/helpers_test.go
controllers/lagoonbuild_controller.go

The domain name of this URL is (almost) guaranteed to be less than 63 chars in length, so it can be used as a CN in certificate requests.
The use of base32 is an attempt to increase the entropy of the 8 character string over simple hex encoding, in order to reduce the likelihood of collisions. Not sure how necessary it is, really.
This is part of a fix for https://github.com/amazeeio/lagoon/issues/2310

feat: add SHORT_ROUTER_URL to the build environment

---

controllers/lagoonbuild_controller.go
main.go

This PR adds CLI options to inject a `securityContext` into the build pod (disabled by default).
This is part of the work for https://github.com/amazeeio/lagoon/pull/2481

feat: add options to set the build pod security context

---

config/default/manager_auth_proxy_patch.yaml
controller-test.sh
handlers/pod_cleanup.go
main.go
test-resources/example-project2.yaml

This adds 2 cronjobs to the manager
* Build pod cleanup
* Runs every hour on the hour
* Retains 1 pod per namespace that isn't running/pending
* Task pod cleanup
* Runs every hour on the half hour
* Retains 1 pod per namespace that isn't running/pending
These are all configurable with flags
```
#builds defaults
--enable-build-pod-cleanup=true
--build-pod-cleanup-cron="0 * * * *"
--num-build-pods-to-keep=1
#tasks defaults
--enable-task-pod-cleanup=true 
--task-pod-cleanup-cron="30 * * * *"
--num-task-pods-to-keep=1
```
closes #39

Implement pod cleanup cronjobs

---

go.mod
go.sum

A customer discovered a problem where they had a number of projects that have a suffix that is the same on a large number of their projects (more than 10). But they had 1 project that was the suffix.
With the default goharbor-client library when trying to `GetProjectByName`, it does a ListProjects call, and it seems that the core Harbor API does a regex match and returns all 60+ projects in the response in a paginated response. The goharbor-client library only returns data for page_num 1, with a page_size of 10.
This patched version of the library returns a page_size of 100. Will need to raise an issue with the library maintainer to support pagination properly as a long term fix.

Use patched library to solve page_size issues

---

controllers/lagoonbuild_controller.go
main.go

This PR adds support for specifying the number of hourly backups to retain via k8up.

Adding hourly backup support

---

apis/lagoon/v1beta1/lagoonmessaging_types.go
apis/lagoon/v1beta1/zz_generated.deepcopy.go
config/crd/bases/crd.lagoon.sh_lagoonbuilds.yaml
config/crd/bases/crd.lagoon.sh_lagoontasks.yaml
controllers/v1beta1/build_controller.go
controllers/v1beta1/build_deletionhandlers.go
controllers/v1beta1/build_helpers.go
controllers/v1beta1/build_qoshandler.go
controllers/v1beta1/build_standardhandler.go
controllers/v1beta1/harborintegration.go
controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_controller.go
controllers/v1beta1/podmonitor_taskhandlers.go
go.mod
go.sum
handlers/message_queue.go
handlers/misctask_handler.go
internal/helpers/helpers.go
main.go

Major refactoring around patching operations to try and solve some issues.
Notably, if builds are cancelled via Lagoon, but a build that is complete or failed already in the remote, then remote-controller will attempt to retain this when responding back to Lagoon, otherwise it will fall back to cancelling.
closes #75
closes #121

Refactor resource patching

---

controllers/messenger/deletions.go
controllers/messenger/queues.go

When volumes are deleted, but there is a Job that had mounted it, the namespace is never deleted due to the Job holding the volume. This adds a step to clean up potential Jobs that may be holding a volume.
closes #139

delete jobs in the namespace too to prevent hold ups

---

controllers/v1beta1/build_controller.go
controllers/v1beta1/build_helpers.go
controllers/v1beta1/task_controller.go
main.go

We currently inject `TASK_API_X` and `TASK_SSH_X` variables into tasks so that they can consume the API if required.
Builds should also have this injected, so that there is less reliance on having the `.lagoon.yml` file needing to be populated with the API/SSH endpoints (see https://docs.lagoon.sh/using-lagoon-the-basics/lagoon-yml/#api and https://docs.lagoon.sh/using-lagoon-the-basics/lagoon-yml/#ssh).
The new variables are as folllows, in addition to this, these are also now injected into tasks alongside the `TASK_` versions so that we can deprecate those in time.
* `LAGOON_CONFIG_API_HOST`
* `LAGOON_CONFIG_SSH_HOST`
* `LAGOON_CONFIG_SSH_PORT`
Will need to raise follow up issue in other repositories for things that consume the `.lagoon.yml` in remote systems to have them updated to …

feat: inject lagoon api/ssh config into builds

---

controller-test.sh
internal/harbor/harbor21x.go
internal/harbor/harbor22x.go
internal/harbor/harborintegration.go
internal/harbor/harborintegration_test.go
main.go
test-resources/example-project1.yaml
test-resources/example-project2.yaml

Some cases it is useful to know which cluster generated the robot account. This is especially handy when doing migrations that share the same harbor.
This adds the cluster name to the robot account name.
Now robot accounts will be named like so, with a hashed version of the cluster name. A description is also added to the account to indicate which cluster it is in.
```
robot$environment-abc123df
robot$project+environment-abc123df
```

use cluster names in robot account names

---

main.go

There may be times where the 30d interval and the job to rotate credentials of 30d may not line up properly if running all the default interval configurations for credentials.
Changing the default interval to 1d will mean that credentials are rotated earlier to try reduce issues.

chore: change the default rotate interval to be 1d instead of 30d

---

controllers/messenger/deletions.go
controllers/messenger/queues.go

In some cases deleting jobs and deployments etc may still leave a pod lingering. This adds support to delete any remaining pods.

feat: add support to delete any pods that might be remaining

---

internal/namespace-utilities/ns-pruner.go
internal/utilities/namespace-pruner.go
main.go

The following adds a cronjob that will, every 30 minutes (by default), check namespaces for the existence of a label 
`lagoon.sh/expiration=<unixtimestamp>` that will delete the namespace if the current time is > than the timestamp on the label.
This is to be used to clean up old namespaces automatically.

Feature: namespace cleanup job

---

controllers/v1beta1/build_helpers.go
controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_taskhandlers.go

As #173 explains, if a build log exceeds the size of what can be stored in a resource, it can fail to update the lagoon API and cause build processing to stall. 
This PR disables patching the resource with the build log to prevent this issue from occurring. There is an existing `pending` place holder that can also store this, which has a hard limit of 1MB of build logs, but this is only ever used if the queue goes down. Eventually I think this functionality can also be removed.
closes #173

refactor: don't save build logs in resource

---

controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_taskhandlers.go
internal/utilities/pruner/old_process_pruner.go
internal/utilities/pruner/old_process_pruner_test.go
internal/utilities/pruner/pruner.go
main.go

This introduces functionality to delete long running tasks and builds, the default termination value is 6 hours. This is adjustable via flags. It is enabled by default.
There is the ability to label namespaces with additional labels that can override the default, eventually these will be configurable in the Lagoon API though.
closes #182

Feature: Terminate long running builds and tasks

---

controllers/v1beta1/build_controller.go
controllers/v1beta1/build_helpers.go
controllers/v1beta1/task_controller.go

Currently, advanced tasks don't mount the "lagoon-env" configmap, and so some variables that should legitimately be available to the task aren't. This PR adds it.

Feature: add lagoon-env configmap to advanced task spec

---

.github/workflows/remote-controller.yaml
controllers/v1beta1/build_helpers.go
controllers/v1beta1/task_controller.go

The `lagoon-deployer` service account token is not created in kubernetes 1.24 via `kind: Secret` anymore. Kubernetes has supported bound tokens for a few versions now.
This PR supports mounting the legacy token if it exists (for clusters and environments created prior to kubernetes 1.24), but will still provide the bound token via projected volume mounts by running the pod with the `lagoon-deployer` service account.
The following PRs address changing the location for the bound token, but still allowing for legacy to be used.
* https://github.com/uselagoon/build-deploy-tool/pull/140
* https://github.com/uselagoon/lagoon/pull/3325
These will have to exist for some time for transitioning
closes #151

refactor: support for legacy and bound serviceaccount tokens

---

main.go

kubectl-build-deploy-dind image has not been used for some time. This updates the default image to be the latest build-deploy-image instead.

chore: change the controller to use the latest build-deploy-image

---

controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_taskhandlers.go

When trying to save the status message/log information of a build or task, the merge data that would be saved in the CRD was missing a field definition.
This adds that missing field

fix: ensure statusmessages field exists

---

controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_taskhandlers.go
internal/helpers/helpers_test.go

In some cases, a lagoonbuild or lagoontask may not exist when a pod is cleaned up (the pod got detached from the build/task some how) so some additional steps should be taken to handle these

fix: missing lagoonbuild or lagoontask resources

---

main.go

If utilising the proxy configuration in the controller, if using `no_proxy`, the actual inserted value is of the `http_proxy`, this fixes it so that the right `no_proxy` value is used.

fix: use the right no proxy variable

---

apis/lagoon/v1beta1/lagoonbuild_types.go
apis/lagoon/v1beta1/lagoontask_types.go
controllers/v1beta1/build_controller.go
controllers/v1beta1/build_deletionhandlers.go
controllers/v1beta1/build_helpers.go
controllers/v1beta1/build_qoshandler.go
controllers/v1beta1/build_standardhandler.go
controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_controller.go
controllers/v1beta1/podmonitor_taskhandlers.go
controllers/v1beta1/task_controller.go
internal/helpers/helpers.go
internal/messenger/consumer.go
internal/messenger/tasks_handler.go

This adds a log message to any builds that are currently in the queue for QoS, and updates their status to `pending`. Once https://github.com/uselagoon/lagoon/pull/3351 is supported in lagoon, this can be updated to use `queued` instead.

feat: add log for queue position to queued builds

---

controller-test.sh
internal/messenger/consumer.go

Add support for `deploytarget:` as a key level for misc tasks in remote-controller, still support the old key types though for now

chore: support new key type for deploytarget

---

controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_taskhandlers.go

Addresses https://github.com/uselagoon/build-deploy-tool/issues/163
Included node & cluster information in the head of the build logs.

Feature: Include node & cluster info in build logs

---

apis/lagoon/v1beta1/lagoonmessaging_types.go
apis/lagoon/v1beta1/zz_generated.deepcopy.go
config/crd/bases/crd.lagoon.sh_lagoonbuilds.yaml
config/crd/bases/crd.lagoon.sh_lagoontasks.yaml
controllers/v1beta1/build_deletionhandlers.go
controllers/v1beta1/podmonitor_buildhandlers.go

The monitoring urls feature hasn't been used for awhile, as it was replaced with monitoring paths. The api will stop storing this information soon, so there is no need to send it back.
Part of https://github.com/uselagoon/lagoon/issues/2975

Remove MonitoringURLs support

---

controllers/v1beta1/build_helpers.go
controllers/v1beta1/build_qoshandler.go

When checking pending builds, there was a case where the controller would not update pending builds as pending or queued because the build process was returning due to another function.
Also some additional debug messaging if required
closes #200

fix: actually update pending or queued builds

---

controller-test.sh
controllers/v1beta1/task_controller.go
test-resources/dynamic-secret-in-task-project1-secret.yaml
test-resources/dynamic-secret-in-task-project1.yaml

In https://github.com/uselagoon/build-deploy-tool/pull/148 we added the ability to mount dynamic secrets into the build.
This needs to be duplicated for advanced tasks - and so this replicates the logic found in the build-deploy legacy tooling.
Explain the **details** for making this change. What existing problem does the pull request solve?

feat: add dynamic secrets to task controller

---

controllers/v1beta1/build_deletionhandlers.go

Fixes a bug where the endtime is sent during builds when it shouldn't be.
closes https://github.com/uselagoon/lagoon-ui/issues/124

fix: only update end time if build is complete, failed, or cancelled

---

controllers/v1beta1/build_helpers.go
controllers/v1beta1/harborcredential_controller.go
controllers/v1beta1/predicates.go
internal/harbor/harbor21x.go
internal/harbor/harbor22x.go
internal/harbor/harbor_credentialrotation.go
internal/harbor/harbor_helpers.go
main.go

The controller will now watch secrets with the `lagoon.sh/controller` label, and by adding a `harbor.lagoon.sh/force-rotate=true` label on a `lagoon-internal-registry-secret` Secret the controller will now regenerate the credentials.
closes #208 (mostly)

feat: support being able to force rotate robot account credentials

---

controllers/v1beta1/podmonitor_buildhandlers.go
internal/messenger/tasks_handler.go

When cancelling a build via the API, the controller will try and collect any information it can about a build if the information still exists in the remote cluster. This could be a build pod, or the lagoon-build resource itself depending on which exists.
As much information from either of these two should be retrieved when possible and sent back to the api so that the API can try to be correct.

chore: try to retain existing build information when cancelling

---

controllers/v1beta1/podmonitor_buildhandlers.go

Currently builds will switch between using the build resource uuid and the build pod uuid as the `remoteId` that lagoon uses to display logs, but not on purpose. This can cause some logs to be lost when recalled as the remoteId changes during a build from one to another.
This PR fixes it by ensuring that all logs use the uuid of the build resource.

chore: make sure builds use the build resource uid

---

controllers/v1beta1/podmonitor_taskhandlers.go

To try and reduce race conditions of the last pod status change and the final completion message for a task, introduce a small sleep delay.

chore: small sleep to delay final message

---

internal/harbor/harbor21x.go
internal/harbor/harbor22x.go
internal/harbor/harbor_helpers.go
internal/harbor/harbor_helpers_test.go

Some environments in Lagoon can be deployed with double dashes in their name. While this is supported (but not something encouraged), Harbor 2.2.0+ has enforcement on robot account names, which makes environments with double dashes invalid. Previous versions of Harbor allowed this so it went unknown until recently.
Now the process will validate the robot account name, and change it to use hashed environment name if the supplied name is invalid.
closes #215

fix: harbor robot account name generation for environments with double dash

---

controllers/v1beta1/build_controller.go
controllers/v1beta1/build_helpers.go
controllers/v1beta1/task_controller.go
go.mod
internal/helpers/config_helpers.go
internal/helpers/helper_types.go
main.go

#146 introduced `LAGOON_CONFIG_X` variables to be injected into tasks and builds. so far these have not been used by the `build-deploy-tool`, but https://github.com/uselagoon/build-deploy-tool/pull/193 plans to introduce these in the future (that PR will be updated to reflect these changes).
This PR is changing `TASK_SSH_HOST/PORT` to now be the token service address, and introduces `LAGOON_CONFIG_TOKEN_HOST/PORT`. These will be used by [tasks resolvers](https://github.com/uselagoon/lagoon/blob/749a3f6a8290d318b71f3f824b189ed8c03cc93d/services/api/src/resources/task/resolvers.ts#L438) soon too.
`LAGOON_CONFIG_SSH_HOST/PORT` has been changed to now be the regional ssh portal address definition. In a lagoon-remote installation via helmchart, this can be defined as the internal service name …

refactor: change up the TASK_X and LAGOON_CONFIG_X variable injection

---

internal/messenger/tasks_handler.go

When cancelling a build where the build resource doesn't exist, a nil pointer reference error is encountered. This checks the build exists before trying to access the resources.

fix: check the build resource is present

---

internal/messenger/tasks_handler.go

When cancelling a task that no longer exists in the cluster, we need to pass back some values in the response so the actions-handler knows how to cancel the task properly.
Part of https://github.com/uselagoon/lagoon/pull/3112 but can be merged and released prior to the core pullrequest

chore: make sure we pass the right values back to core when cancelling a task

---

apis/lagoon/v1beta1/lagoontask_types.go
config/crd/bases/crd.lagoon.sh_lagoonbuilds.yaml
config/crd/bases/crd.lagoon.sh_lagoontasks.yaml
internal/messenger/tasks_handler.go
main.go

Deprecates the older injection flags that were added for support before the Lagoon API had proper support for providing these values. Now that the API has provided these for some time, we should use these instead.

refactor: use injection from the task data from the lagoon api

---

internal/harbor/harbor.go
internal/harbor/harbor22x.go

The harbor client library used doesn't set a default page number to start with so assumes 0. This results in the library not properly iterating over the pages and not returning all the robot accounts. This corrects the bug by setting the default page number to be 1

fix: set the default page to be 1 so that pagination works properly

---

internal/harbor/harbor22x.go
internal/utilities/deletions/deletions.go
internal/utilities/deletions/process.go

When migrating environments between clusters, if harbor cleanup is enabled, when the source environment is deleted, it will delete the images that the destination environment uses.
This adds labels that can be added to the source environment `lagoon-internal-registry-secret` secret, that will make sure that the remote-controller won't remove the images from harbor when the environment is eventually pruned.
closes #60

refactor: allow overriding harbor cleanups by labelling secret

---

controllers/v1beta1/build_deletionhandlers.go
controllers/v1beta1/build_helpers.go
controllers/v1beta1/build_qoshandler.go
controllers/v1beta1/podmonitor_buildhandlers.go

This adds a `queued 1/1` build step to queued builds, but also corrects a problem with builds that fail but the buildstep still shows as `running` which would be confusing
```
{
"name": "lagoon-build-nhl0y",
"status": "failed",
"buildStep": "running"
},
```

refactor: send better buildstep messages for queued and failed builds

---

controllers/v1beta1/build_controller.go
controllers/v1beta1/build_deletionhandlers.go
controllers/v1beta1/build_helpers.go
controllers/v1beta1/build_qoshandler.go
controllers/v1beta1/build_standardhandler.go
controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_controller.go
controllers/v1beta1/podmonitor_taskhandlers.go
internal/helpers/helpers.go

As #223 describes, sometimes the kubernetes API can be unresponsive, we've typically only seen this an Azure clusters, and it prevents the controller from reconciling or updating builds properly.
This adds a function to the controller that now when a new build is received, it will check the namespace for running builds, and then attempt to determine if there is a pod associated to that running build or not and then attempt to update the resource and update Lagoon with the change.
closes #223 
closes #160

feat: when a new build comes in, check the namespace for running builds to determine state

---

controllers/v1beta1/build_helpers.go
controllers/v1beta1/build_helpers_test.go
controllers/v1beta1/build_qoshandler.go
controllers/v1beta1/podmonitor_controller.go
controllers/v1beta1/task_controller.go
go.mod
internal/helpers/helpers.go
main.go

Refactoring build queue process to reduce the amount of times that events trigger actions when QoS is enabled.
There were points in the event cycle where when a build completes, it would pick an item from the queue, but if there was also a pending build in the namespace that triggered the event, it would start a build in that namespace too. This allowed clusters to exceed the QoS limit.
This also introduces some additional changes to the way the queue is handled with the sorting function working as it should now by sorting by priority and creation time, and also allows events to trigger period updates of the pending items in a blocking operation

refactor: split queue process out

---

.github/workflows/remote-controller.yaml
Makefile
controllers/v1beta1/build_controller.go
controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_controller.go
controllers/v1beta1/podmonitor_taskhandlers.go
go.mod
go.sum
internal/messenger/consumer.go
internal/messenger/messenger.go
main.go

There exists a condition where a cancellation can be actioned before the task or build has been started, so that when the task or build are started they have no idea that it was cancelled. This is because there are two queues used, one for builds and tasks, the other for misc tasks. Cancellations enter via the misc queue, and because they are handled in their own queue, it is possible that the cancellation message could be processed before the build or task message is handled completely.
This implements an expiring cache that will cache cancellations, so that if the condition is met and the pod gets started, the pod controller will check the cache periodically and if the cancellation exists in cache will cancel the task or build in the way it would normally be cancelled.

fix: cache cancellations to prevent race conditions in pod creation

---

apis/lagoon/v1beta1/lagoontask_types.go
config/crd/bases/crd.lagoon.sh_lagoonbuilds.yaml
config/crd/bases/crd.lagoon.sh_lagoontasks.yaml
internal/messenger/tasks_handler.go

This reverts the changes made in #225 and implements a custom unmarshal function to convert the 1|0 bools to golang booleans
Since the main chart CRDs were never updated, the CRD change within this is somewhat acceptable to revert for now since the recommended install method is via helm.

fix: revert and fix the deployertoken injection using a custom unmarshal

---

config/default/manager_auth_proxy_patch.yaml
internal/messenger/messenger.go
internal/messenger/tasks_restore.go
main.go

This feature wraps the support for k8up v2 (k8up.io/v1 crds) restores, and disabled by default.

chore: flag wrap k8upv2 support

---

.github/workflows/remote-controller.yaml

Drops kubernetes 1.21 and 1.22 from tests

chore: set kubernetes versions in tests to 1.23 starting point

---

internal/messenger/tasks_handler.go

Small fix to make sure advanced tasks are created using their lagoon-task name instead of a custom advanced task name. The lagoon.sh labels identify if it is an advanced or standard task already.

fix: use the lagoon task name for advanced tasks for cancellations to work

---

internal/messenger/consumer.go
internal/messenger/tasks_handler.go

Just some additional fixes for the newer active/standby task to properly base64 decode the payload before the json unmarshal runs

fix: add more support for newer active-standby switch task

---

internal/utilities/deletions/process.go

This introduces new retaining labels that can be added to the harbor secret, or the namespace, that will inform the deletion handler to not clean up resources in harbor when a namespace is deleted.
The following labels can now be added to the namespace or the internal registry secret that Lagoon uses to prevent resources being deleted in harbor when a namespace is deleted in kubernetes. This would mostly used if you're migrating an environment between two clusters that may share the same harbor. If they're different harbors, then you probably don't need to use these at all.
* `harbor.lagoon.sh/retain-repositories`
* `harbor.lagoon.sh/retain-robotaccount`
---
These two labels were created for this purpose initially. These labels are now deprecated, and you should use the new ones
* …

feat: introduce new retain harbor resources labels and deprecate old ones

---

controllers/v1beta1/build_controller.go
controllers/v1beta1/build_helpers.go
main.go

With https://github.com/uselagoon/lagoon/pull/3659, core removed the support for this passthrough. This implements the passthrough in the remote-controller now for backwards compatibility for now.
This may get refactored again though if we revisit supporting more than Harbor in Lagoon remote clusters.

refactor: add basic unauthenticated registry passthrough

---

Dockerfile
controllers/v1beta1/podmonitor_buildhandlers.go
controllers/v1beta1/podmonitor_taskhandlers.go
internal/helpers/helpers.go

If a pod fails in kubernetes with an ImagePullBackOff or CrashLoopBackOff, the controller would not pick this up and return the failure to the message queue.
This has a check for the pod failure status now so that a failure of either of these types will return to Lagoon the reason for the failure.

fix: if pod fails send failure correctly

---

apis/lagoon/v1beta1/lagoontask_types.go

Just a quick fix for v1beta1 tasks marshaling for backwards compatibility

fix: add json marshal for v1beta1 tasks

---

apis/lagoon/v1beta2/lagoontask_types.go

Fixes a bug when trying to list tasks where v1beta1 still contains string ids instead of uint.

fix: add json unmarshal fix for v1beta1 retrieving as v1beta2

---

Dockerfile
internal/controllers/v1beta2/build_controller.go
internal/controllers/v1beta2/build_helpers.go
internal/controllers/v1beta2/build_qoshandler.go
internal/controllers/v1beta2/podmonitor_buildhandlers.go

Modifies the queue processor to only run when a build is created, cancelled, failed, or completed. Previously it would run on any update which could result in excessive attempts to try and reconcile builds during high activity periods.
Additionally, updates the CR for cancellations. Also the `BuildStep` status condition remains, but all other buildsteps will also be their own condition now to retain the full build step transitions of a build in the CR

refactor: queue processing and build conditions

---

internal/controllers/v1beta2/build_helpers.go
internal/controllers/v1beta2/podmonitor_buildhandlers.go
internal/controllers/v1beta2/podmonitor_taskhandlers.go
internal/helpers/helpers.go
internal/helpers/helpers_test.go

Refactor the status conditions to validate and adjust on errors as required, mostly to help with https://github.com/uselagoon/build-deploy-tool/pull/390

refactor: status condition validations

---

internal/controllers/v1beta2/build_controller.go
internal/controllers/v1beta2/build_deletionhandlers.go
internal/controllers/v1beta2/build_helpers.go
internal/controllers/v1beta2/podmonitor_buildhandlers.go
internal/controllers/v1beta2/task_controller.go
internal/helpers/helpers.go

Support for https://github.com/uselagoon/build-deploy-tool/pull/397

refactor: check for lagoon-env secrets first

---

internal/controllers/harbor/harborcredential_controller.go
internal/controllers/v1beta2/build_helpers.go
internal/harbor/harbor_credentialrotation.go

Fixes a missed rotated credential check from #288 (https://github.com/uselagoon/remote-controller/pull/288/files#diff-487cd9eccb6a4367ed44e85119021df097dc1793b120a6a58b1a29bf331fcd54R91) that needed to be added to the `build_helpers.go` file to support checking if the credential was actually rotated. Instead I replaced the duplicated logic with the `RotateRobotCredential` call which already handled this.

fix: check the returned credentials before using

---

api/lagoon/v1beta2/lagoonbuild_helpers.go
internal/controllers/v1beta2/build_controller.go
internal/controllers/v1beta2/build_deletionhandlers.go
internal/controllers/v1beta2/build_qoshandler.go
internal/controllers/v1beta2/build_standardhandler.go
internal/controllers/v1beta2/buildpodmonitor_handlers.go

Refactors the way the build pod deletion process runs to reduce the potential for duplicate messages due to a race condition in the previous implementation.
closes #289 
closes #290

refactor: build pod deletion to reduce duplicate messages

---

.github/workflows/remote-controller.yaml
Dockerfile
Makefile
cmd/main.go
internal/controllers/v1beta2/build_controller.go
internal/controllers/v1beta2/build_helpers.go
internal/controllers/v1beta2/buildpodmonitor_controller.go
internal/controllers/v1beta2/buildpodmonitor_handlers.go
internal/dockerhost/dockerhost.go
internal/dockerhost/dockerhost_test.go
internal/metrics/metrics.go

With the support for multiple dockerhosts being made [available](https://github.com/uselagoon/lagoon-charts/pull/687) in `lagoon-remote`. The `remote-controller` behaviour was previously to send builds to the main service that would use session to distribute amongst the dockerhosts.
This feature will now allow the remote-controller to detect the available dockerhosts in a remote and how many there are, and attempt to distribute builds amongst them.
The preference will be to assign a build for an environment to the same dockerhost that previous builds for that environment were built on to benefit from caching. During the event though where there is a lot of builds on that host and others are less used, the process will pick a dockerhost that has less builds on it to prevent congestion on a …

feat: support multiple docker hosts with dockerhost service injection

---

.github/workflows/build_and_publish.yml

Until dockerhub supports the OCI Referrers API, attestations attached to
images result in numerous noisy sha256-* tags. So disable dockerhub
image attestation for now.

chore: disable dockerhub image attestation

---

.github/workflows/remote-controller.yaml

To help improve test speed, this reduces the number of kubernetes and harbor versions tested.
We should look to do this periodically.

test: reduce number of kubernetes versions to test

---

.github/workflows/remote-controller.yaml
Makefile
go.mod
go.sum
internal/harbor/harbor_robot.go
internal/utilities/deletions/process.go
test/e2e/e2e_test.go

The client library we use for Harbor doesn't directly support querying for project robot accounts, which is used by the remote-controller and Lagoon to create robot accounts.
Refactored the client creation to include query parameter overrides to set the query for project level queries for robot accounts.
closes #307

feat: support for harbor 2.13.x

---

cmd/main.go
internal/controllers/v1beta2/build_controller.go
internal/controllers/v1beta2/build_helpers.go
internal/controllers/v1beta2/task_controller.go

This adds a new feature that will add the label `cluster-autoscaler.kubernetes.io/safe-to-evict` ([see more](https://kubernetes.io/docs/reference/labels-annotations-taints/#cluster-autoscaler-kubernetes-io-safe-to-evict)) to build and task pods with the value `false`.
This is done to prevent build pods from being evicted by cluster autoscaler. This flag is disabled by default, meaning build and tasks pods will (hopefully) not be evicted, you can enable it if you do want pods to be evicted.

feat: default label to prevent autoscaler evictions on pods

---

internal/messenger/build_handler.go

Spotted in the wild, if a namespace is stuck terminating and a build comes through for that namespace again, the remote-controller crashes with a panic nil pointer error until the namespace is cleaned up. This prevents new builds from processing as the controller continues to crash and the build is never removed from the messagequeue.
This fixes the points that caused the nil pointer issue, and also fixes the missing `UID` in the build so that the logs for these builds appear in the API correctly.

fix: build cleanup on creation
