controllers/lagoonbuild_controller.go, controllers/lagoonmonitor_controller.go, go.mod, go.sum, handlers/message_queue.go, main.go
=> Add MQ retry when starting

controllers/lagoontask_controller.go, main.go
This adds initial support for TASK_X variables so the controller can inject the known lagoon endpoints into tasks that it runs.
```
TASK_API_HOST
TASK_SSH_HOST
TASK_SSH_PORT
```
Normally it would check inside the task spec, but this may not always contain a value.
=> Support TASK_X variable overrides

api/v1alpha1/lagoonbuild_types.go, charts/lagoon-builddeploy/templates/crd.yaml, config/crd/bases/lagoon.amazee.io_lagoonbuilds.yaml
=> change pullrequest.number to a string instead of int

handlers/message_queue.go
=> remove backup-id from misc tasks

handlers/message_queue.go
=> Continue with deletion if the namespace is not found

handlers/message_queue.go
Lagoon sends a different payload for pullrequest deletions which contain a field called `branchName` not `branch` like others.
This PR fixes it so that if the `Type` is `pullrequest` it will use the value of `branchName` to handle deletions.
=> Fix PR environment deletions

config/default/envs.yaml, controller-test.sh, controllers/lagoonbuild_controller.go, controllers/lagoonbuild_handlers.go, controllers/lagoonmonitor_controller.go, controllers/lagoontask_controller.go, controllers/lagoontask_handlers.go, handlers/message_queue.go, handlers/misctask_handler.go, main.go, test-resources/example-project1.yaml
Change some info logs to error logs to better represent what they are.
Add some additional error checks for json marshalling and add logging for these too.
=> Changes to logging

controllers/helpers.go, controllers/lagoonbuild_controller.go, controllers/lagoonbuild_deletionhandlers.go, controllers/lagoonbuild_handlers.go, controllers/lagoonmonitor_buildhandlers.go, controllers/lagoonmonitor_controller.go, controllers/lagoonmonitor_taskhandlers.go, handlers/misctask_handler.go, main.go
=> Add pending check after build pods or LagoonBuilds are deleted

controllers/lagoonbuild_controller.go, main.go
These feature flags integrate with these Lagoon PRs:
* https://github.com/amazeeio/lagoon/pull/2523
* https://github.com/amazeeio/lagoon/pull/2536
They are tested in those PRs too.
The feature flags are documented here:
* https://github.com/amazeeio/lagoon/pull/2541
And chart support was added here:
* https://github.com/uselagoon/lagoon-charts/pull/234
=> Add feature flags for new Lagoon features

controllers/lagoonmonitor_buildhandlers.go
When converting the old `kubernetesbuilddeploymonitor` into the controller, a step was missed that crafts the slack message and adds the routes and log link. Slack is the only notification service I can see that does this differently (see notes below)
This adds those missing features to the message.
Ideally, the entire notification service in Lagoon should be re-written so this `Message` block isn't required and the entire block from the controller is omitted. 
The notification service in Lagoon should craft the information it needs from the other `Meta` fields to make for a more consistent messaging across multiple notification services.
=> Add missing routes and log link to message

controller-test.sh, handlers/delete_handler.go, handlers/message_queue.go
=> Clean up env before deleting namespaces

controllers/lagoon_harborintegration.go, controllers/lagoonbuild_controller.go, main.go
=> Additional Harbor credential fixes

controllers/lagoon_harborintegration.go
=> Check secret for robot account, recreate if it isn't found

controllers/lagoonbuild_controller.go, main.go
This PR adds support for custom, per-cluster backup schedules in k8up.
=> Adding custom backup schedule support

handlers/delete_handler.go
=> Load PersistentVolumeClaims not PersistentVolumes

main.go
=> refactor: use kebab-case for flags

api/v1alpha1/lagoonmessaging_types.go, controllers/lagoonbuild_controller.go, controllers/lagoonbuild_deletionhandlers.go, controllers/lagoonmonitor_buildhandlers.go, controllers/lagoonmonitor_controller.go, controllers/lagoonmonitor_taskhandlers.go, controllers/lagoontask_controller.go, main.go
=> feat: add cluster to log meta

controllers/v1beta1/lagoonbuild_controller.go, controllers/v1beta1/lagoonbuild_helpers.go, controllers/v1beta1/lagoontask_controller.go, main.go
=> feat: add http proxy variables to build pods

controllers/v1beta1/lagoonbuild_controller.go, controllers/v1beta1/lagoonbuild_helpers.go, main.go
Add support for https://github.com/uselagoon/lagoon/pull/3038
=> feat: add rwx to rwo flag

controllers/v1beta1/helpers.go, controllers/v1beta1/lagoonbuild_controller.go, controllers/v1beta1/lagoonbuild_helpers.go
=> Dont nuke manually cancelled build logs if they are available

controllers/v1beta1/lagoonbuild_controller.go, controllers/v1beta1/lagoonbuild_helpers.go, main.go
Adding support for https://github.com/uselagoon/lagoon/pull/3087
closes #125
=> chore: add dev and pr environment backup overrides

apis/lagoon/v1beta1/lagoonbuild_types.go, controllers/v1beta1/lagoonbuild_controller.go, controllers/v1beta1/lagoonbuild_helpers.go, controllers/v1beta1/lagoontask_controller.go, main.go
=> chore: remove openshift 3.11 support

controllers/v1beta1/lagoonbuild_qoshandler.go
Explain the **details** for making this change. What existing problem does the pull request solve?
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> fix: use the right value for pending builds

handlers/message_queue.go
Crash the controller if there are any errors with the queue, but after some time incase it recovers
=> crash if queue goes away

controllers/v1beta1/build_helpers.go
Explain the **details** for making this change. What existing problem does the pull request solve?
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> add some additional error messaging

controllers/messenger/deletions.go, controllers/messenger/queues.go, main.go
=> Allow for configurable PVC clean up attempts

controllers/messenger/deletions.go
When deleting resources, ignore the error if the error is resource not found (likely was removed before the controller got to it)
=> chore: ignore not found when deleting

controllers/messenger/deletions.go, controllers/messenger/queues.go
Previously deletions would only be processed one by one by the controller, this would delay the deletion of subsequent environments while waiting for others to be processed.
Now it runs the deletion in a separate goroutine, so that processing of other deletions can occur.
closes #166
=> refactor: pull from queue and process to continue handling deletions

.github/workflows/remote-controller.yaml, controllers/v1beta1/podmonitor_buildhandlers.go
=> fix: dont cancel complete or failed builds from pods

apis/lagoon/v1beta1/lagoonbuild_types.go, apis/lagoon/v1beta1/zz_generated.deepcopy.go, controllers/v1beta1/build_helpers.go
Just minor to add new lables for showing if idling is enabled or disabled using true/false
=> chore: add new lables for idling with true/false instead of 1/0

apis/lagoon/v1beta1/lagoonbuild_types.go, config/crd/bases/crd.lagoon.sh_lagoonbuilds.yaml
=> fix: use the right field name

internal/utilities/deletions/kubernetes.go, internal/utilities/deletions/process.go
=> chore: delete ingress in the namespace too

controllers/v1beta1/podmonitor_buildhandlers.go
=> refactor: use deployment instead of pods to get services

.github/workflows/remote-controller.yaml
Updates the harbor chart version in testing to v1.13.1
=> chore: update harbor to chart 1.13.1

internal/harbor/harbor.go, main.go
Just a simple fix to move the insecure skip verify
=> fix: insecure skip verify check for harbor with invalid

.github/workflows/remote-controller.yaml
Update the versions of kubernetes used in tests to v1.25.0+ only
Reduce number of older versions of harbor and kube matrix tests.
=> test: update kubernetes versions

internal/utilities/pruner/old_process_pruner.go
Fix to the build and task pruner to avoid assigning values to nil in the update by changing the operator to patch with merge.
=> fix: build-task limit pruner to use patch merge

.github/workflows/remote-controller.yaml, .gitignore, Makefile, test/e2e/e2e_test.go, test/utils/utils.go
Add targets for tools used in local-development. 
Adjust paths to use those tools and other missing bits for local-development
=> chore: add local-dev tools

Makefile, cmd/main.go, config/default/envs.yaml, config/default/manager_auth_proxy_patch.yaml, docker-compose.yml, go.mod, test-resources/Dockerfile.broker, test-resources/broker-tls.conf, test-resources/definitions.json, test-resources/enabled_plugins, test-resources/start-rabbit.sh, test/utils/utils.go
This extends remote-controller to support AMQPS connections properly.
=> chore: rabbitmq tls support

internal/controllers/v1beta2/build_deletionhandlers.go
This just brings the other messages that are sent for builds to the same dataset being returned to core for builds.
=> refactor: include environment and project id in return metadata
